### PR TITLE
Enforce stricter style requirements.

### PR DESCRIPTION
**Pull request by alexwaibel**
Add a lot more rules to ESLint and Prettier to allow them to work better together and more properly adhere to Airbnb style guide. Also require Prettier check to pass for all Travis builds.

### CODE REVIEW

**Review by Dyrk33 — COMMENTED** [review]
Is there a reason that nodemon was moved from repository to devDependencies in package.json?

**Comment by alexwaibel** [comment]
It was moved because nodemon is only needed on dev. It's the thing that auto refreshes node on code change.

**Review by Dyrk33 — APPROVED** [review]
Looks gucci my main taco

**Review by shoafj7917 — APPROVED** [review]
I like

**Pull request merged**
